server:
  port: 8050
spring:
  application:
    name: account
  datasource:
    url: jdbc:mysql://localhost:3306/takeout
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:/mapping/*.xml

